<div id="filter-top-bar" class="btn-group">
    <nav>
        <ul class="menu filter-options">
            <?php
            echo '<li><a href="javascript:void(0);" class="filter-btn" data-filter="*">ALL</a></li>';
            $topMenuArr = $block->getLayerFilterable();
            foreach ($topMenuArr as $k) {
                echo '<li><a href="javascript:void(0);" class="btn btn--primary">'.$k['name'].'</a><ul class="sub-menu">';
                foreach ($k['data'] as $optionValue) {
                    echo '<li><a href="javascript:void(0);" data-filter=".'.strtolower($k['code']).'-'.$optionValue['label'].'" data-value="'.$optionValue['label'].'" class="btn btn--primary filter-btn">'.$optionValue['display'].' ('.$optionValue['count'].')</a></li>';
                }
                echo '</ul></li>';
            }
            ?>
        </ul>
    </nav>
</div>
